### ISSUE TITLE
unable to "sbt run", No main class detected

### ISSUE THREAD

**Issue by alanngai** [SandroGrzicic/ScalaBuff#76]
I'm trying to use scalabuf to generate scala code from protofiles, but I'm having trouble getting it to even run.  I'm using scala 2.10.3, sbt 0.13.1, and java 1.7.0_21

after checking out the repo,

$ sbt run
Loading /Users/alan/dev/sbt-0.13.1/bin/sbt-launch-lib.bash
[info] Loading project definition from /Users/alan/work/cloudmon/dev-master/ProtoServer/tools/protobuf-src-gen/src/github.com/SandroGrzicic/ScalaBuff/project
[info] Set current project to scalabuff (in build file:/Users/alan/work/cloudmon/dev-master/ProtoServer/tools/protobuf-src-gen/src/github.com/SandroGrzicic/ScalaBuff/)
java.lang.RuntimeException: No main class detected.
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last scalabuff/compile:run for the full output.
[error](scalabuff/compile:run) No main class detected.
[error] Total time: 0 s, completed Jan 17, 2014 5:15:12 PM

so I ran sbt again to enter the console and ran the following to get the stack trace

> run
> java.lang.RuntimeException: No main class detected.
>     at scala.sys.package$.error(package.scala:27)
> [trace] Stack trace suppressed: run last scalabuff/compile:run for the full output.
> [error](scalabuff/compile:run) No main class detected.
> [error] Total time: 0 s, completed Jan 17, 2014 5:17:10 PM
> last scalabuff/compile:run
> java.lang.RuntimeException: No main class detected.
>     at scala.sys.package$.error(package.scala:27)
>     at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37$$anonfun$26.apply(Defaults.scala:655)
>     at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37$$anonfun$26.apply(Defaults.scala:655)
>     at scala.Option.getOrElse(Option.scala:120)
>     at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defaults.scala:655)
>     at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defaults.scala:654)
>     at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
>     at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
>     at sbt.std.Transform$$anon$4.work(System.scala:64)
>     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
>     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
>     at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
>     at sbt.Execute.work(Execute.scala:244)
>     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
>     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
>     at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
>     at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
>     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:166)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
>     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:166)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>     at java.lang.Thread.run(Thread.java:722)
> [error](scalabuff/compile:run) No main class detected.

**Comment by SandroGrzicic** [comment]
Sorry to hear that. Have you been able to resolve this? I'm hoping a newer release of Spark has a newer Protobuf.

**Comment by Dave1704** [comment]
Hi, currently we are having problems with running our play 2 application, if we import the project into IntelliJ as SBT-module and create a simple Play 2 run configuration. Exactly the error 'No main class detected' appears. Could that be related to this problem?
